import { describe, it } from "node:test";

import type { CarrierBankTransfer } from "../main/events/carrier/CarrierBankTransfer.ts";
import type { CarrierBuy } from "../main/events/carrier/CarrierBuy.ts";
import type { CarrierCrewServices } from "../main/events/carrier/CarrierCrewServices.ts";
import type { CarrierDepositFuel } from "../main/events/carrier/CarrierDepositFuel.ts";
import type { CarrierDockingPermission } from "../main/events/carrier/CarrierDockingPermission.ts";
import type { CarrierFinance } from "../main/events/carrier/CarrierFinance.ts";
import type { CarrierJump } from "../main/events/carrier/CarrierJump.ts";
import type { CarrierJumpCancelled } from "../main/events/carrier/CarrierJumpCancelled.ts";
import type { CarrierJumpRequest } from "../main/events/carrier/CarrierJumpRequest.ts";
import type { CarrierLocation } from "../main/events/carrier/CarrierLocation.ts";
import type { CarrierModulePack, CarrierModulePackBase, CarrierModulePackBuy, CarrierModulePackSell } from "../main/events/carrier/CarrierModulePack.ts";
import type { CarrierNameChange } from "../main/events/carrier/CarrierNameChange.ts";
import type { CarrierShipPack, CarrierShipPackBase, CarrierShipPackBuy, CarrierShipPackSell } from "../main/events/carrier/CarrierShipPack.ts";
import type { CarrierStats, Pack } from "../main/events/carrier/CarrierStats.ts";
import type { CarrierTradeOrder } from "../main/events/carrier/CarrierTradeOrder.ts";
import type { Bounty } from "../main/events/combat/Bounty.ts";
import type { CapShipBond } from "../main/events/combat/CapShipBond.ts";
import type { Died } from "../main/events/combat/Died.ts";
import type { EscapeInterdiction } from "../main/events/combat/EscapeInterdiction.ts";
import type { FactionKillBond } from "../main/events/combat/FactionKillBond.ts";
import type { FighterDestroyed } from "../main/events/combat/FighterDestroyed.ts";
import type { HeatDamage } from "../main/events/combat/HeatDamage.ts";
import type { HeatWarning } from "../main/events/combat/HeatWarning.ts";
import type { HullDamage } from "../main/events/combat/HullDamage.ts";
import type { Interdicted } from "../main/events/combat/Interdicted.ts";
import type { Interdiction } from "../main/events/combat/Interdiction.ts";
import type { PVPKill } from "../main/events/combat/PVPKill.ts";
import type { ShieldState } from "../main/events/combat/ShieldState.ts";
import type { ShipTargeted } from "../main/events/combat/ShipTargeted.ts";
import type { SRVDestroyed } from "../main/events/combat/SRVDestroyed.ts";
import type { UnderAttack } from "../main/events/combat/UnderAttack.ts";
import type { BuyExplorationData } from "../main/events/exploration/BuyExplorationData.ts";
import type { CodexEntry } from "../main/events/exploration/CodexEntry.ts";
import type { DiscoveryScan } from "../main/events/exploration/DiscoveryScan.ts";
import type { FSSAllBodiesFound } from "../main/events/exploration/FSSAllBodiesFound.ts";
import type { FSSBodySignals } from "../main/events/exploration/FSSBodySignals.ts";
import type { FSSDiscoveryScan } from "../main/events/exploration/FSSDiscoveryScan.ts";
import type { FSSSignalDiscovered, SignalType } from "../main/events/exploration/FSSSignalDiscovered.ts";
import type { MaterialCollected } from "../main/events/exploration/MaterialCollected.ts";
import type { MaterialDiscarded } from "../main/events/exploration/MaterialDiscarded.ts";
import type { MaterialDiscovered } from "../main/events/exploration/MaterialDiscovered.ts";
import type { MultiSellExplorationData } from "../main/events/exploration/MultiSellExplorationData.ts";
import type { NavBeaconScan } from "../main/events/exploration/NavBeaconScan.ts";
import type { SAAScanComplete } from "../main/events/exploration/SAAScanComplete.ts";
import type { SAASignalsFound } from "../main/events/exploration/SAASignalsFound.ts";
import type { ReserveLevel, Ring, RingClass, Scan, ScanOther, ScanPlanet, ScanStar, ScanType } from "../main/events/exploration/Scan.ts";
import type { ScanBaryCentre } from "../main/events/exploration/ScanBaryCentre.ts";
import type { Screenshot } from "../main/events/exploration/Screenshot.ts";
import type { SellExplorationData } from "../main/events/exploration/SellExplorationData.ts";
import type { Backpack, BackpackItem } from "../main/events/odyssey/Backpack.ts";
import type { BackpackChange, ChangedBackpackItem } from "../main/events/odyssey/BackpackChange.ts";
import type { BookDropship } from "../main/events/odyssey/BookDropship.ts";
import type { BookTaxi } from "../main/events/odyssey/BookTaxi.ts";
import type { BuyMicroResources, NewBuyMicroResources, OldBuyMicroResources } from "../main/events/odyssey/BuyMicroResources.ts";
import type { BuySuit } from "../main/events/odyssey/BuySuit.ts";
import type { BuyWeapon } from "../main/events/odyssey/BuyWeapon.ts";
import type { CancelDropship } from "../main/events/odyssey/CancelDropship.ts";
import type { CancelTaxi } from "../main/events/odyssey/CancelTaxi.ts";
import type { CollectItems } from "../main/events/odyssey/CollectItems.ts";
import type { CreateSuitLoadout } from "../main/events/odyssey/CreateSuitLoadout.ts";
import type { DeleteSuitLoadout } from "../main/events/odyssey/DeleteSuitLoadout.ts";
import type { Disembark } from "../main/events/odyssey/Disembark.ts";
import type { DropItems } from "../main/events/odyssey/DropItems.ts";
import type { DropshipDeploy } from "../main/events/odyssey/DropshipDeploy.ts";
import type { Embark } from "../main/events/odyssey/Embark.ts";
import type { ExtendedFCMaterials, FCMaterials } from "../main/events/odyssey/FCMaterials.ts";
import type { LoadoutEquipModule } from "../main/events/odyssey/LoadoutEquipModule.ts";
import type { RenameSuitLoadout } from "../main/events/odyssey/RenameSuitLoadout.ts";
import type { ScanOrganic } from "../main/events/odyssey/ScanOrganic.ts";
import type { SellMicroResources } from "../main/events/odyssey/SellMicroResources.ts";
import type { SellOrganicData } from "../main/events/odyssey/SellOrganicData.ts";
import type { SellSuit } from "../main/events/odyssey/SellSuit.ts";
import type { SellWeapon } from "../main/events/odyssey/SellWeapon.ts";
import type { ShipLocker, ShipLockerItem } from "../main/events/odyssey/ShipLocker.ts";
import type { SuitLoadout } from "../main/events/odyssey/SuitLoadout.ts";
import type { SwitchSuitLoadout } from "../main/events/odyssey/SwitchSuitLoadout.ts";
import type { TradeMicroResources } from "../main/events/odyssey/TradeMicroResources.ts";
import type { TransferMicroResources } from "../main/events/odyssey/TransferMicroResources.ts";
import type { UpgradeSuit } from "../main/events/odyssey/UpgradeSuit.ts";
import type { UpgradeWeapon } from "../main/events/odyssey/UpgradeWeapon.ts";
import type { UseConsumable } from "../main/events/odyssey/UseConsumable.ts";
import type { AfmuRepairs } from "../main/events/other/AfmuRepairs.ts";
import type { ApproachSettlement } from "../main/events/other/ApproachSettlement.ts";
import type { CargoTransfer } from "../main/events/other/CargoTransfer.ts";
import type { ChangeCrewRole } from "../main/events/other/ChangeCrewRole.ts";
import type { CockpitBreached } from "../main/events/other/CockpitBreached.ts";
import type { ColonisationConstructionDepot, ColonisationConstructionResource } from "../main/events/other/ColonisationConstructionDepot.ts";
import type { ColonisationContribution, ColonisationContributionResource } from "../main/events/other/ColonisationContribution.ts";
import type { CommitCrime } from "../main/events/other/CommitCrime.ts";
import type { Continued } from "../main/events/other/Continued.ts";
import type { CrewLaunchFighter } from "../main/events/other/CrewLaunchFighter.ts";
import type { CrewMemberJoins } from "../main/events/other/CrewMemberJoins.ts";
import type { CrewMemberQuits } from "../main/events/other/CrewMemberQuits.ts";
import type { CrewMemberRoleChange } from "../main/events/other/CrewMemberRoleChange.ts";
import type { CrimeVictim } from "../main/events/other/CrimeVictim.ts";
import type { DatalinkScan } from "../main/events/other/DatalinkScan.ts";
import type { DatalinkVoucher } from "../main/events/other/DatalinkVoucher.ts";
import type { DataScanned } from "../main/events/other/DataScanned.ts";
import type { DockFighter } from "../main/events/other/DockFighter.ts";
import type { DockSRV } from "../main/events/other/DockSRV.ts";
import type { EndCrewSession } from "../main/events/other/EndCrewSession.ts";
import type { FighterRebuilt } from "../main/events/other/FighterRebuilt.ts";
import type { Friends } from "../main/events/other/Friends.ts";
import type { FuelScoop } from "../main/events/other/FuelScoop.ts";
import type { JetConeBoost } from "../main/events/other/JetConeBoost.ts";
import type { JetConeDamage } from "../main/events/other/JetConeDamage.ts";
import type { JoinACrew } from "../main/events/other/JoinACrew.ts";
import type { KickCrewMember } from "../main/events/other/KickCrewMember.ts";
import type { LaunchDrone } from "../main/events/other/LaunchDrone.ts";
import type { LaunchFighter } from "../main/events/other/LaunchFighter.ts";
import type { LaunchSRV } from "../main/events/other/LaunchSRV.ts";
import type { ExtendedModuleInfo, ModuleInfo } from "../main/events/other/ModuleInfo.ts";
import type { Music } from "../main/events/other/Music.ts";
import type { NpcCrewPaidWage } from "../main/events/other/NpcCrewPaidWage.ts";
import type { NpcCrewRank } from "../main/events/other/NpcCrewRank.ts";
import type { Promotion } from "../main/events/other/Promotion.ts";
import type { ProspectedAsteroid } from "../main/events/other/ProspectedAsteroid.ts";
import type { QuitACrew } from "../main/events/other/QuitACrew.ts";
import type { RebootRepair } from "../main/events/other/RebootRepair.ts";
import type { ReceiveText } from "../main/events/other/ReceiveText.ts";
import type { RepairDrone } from "../main/events/other/RepairDrone.ts";
import type { ReservoirReplenished } from "../main/events/other/ReservoirReplenished.ts";
import type { Resupply } from "../main/events/other/Resupply.ts";
import type { Resurrect } from "../main/events/other/Resurrect.ts";
import type { Scanned } from "../main/events/other/Scanned.ts";
import type { SelfDestruct } from "../main/events/other/SelfDestruct.ts";
import type { SendText } from "../main/events/other/SendText.ts";
import type { Shutdown } from "../main/events/other/Shutdown.ts";
import type { LegalState, Status } from "../main/events/other/Status.ts";
import type { SupercruiseDestinationDrop } from "../main/events/other/SupercruiseDestinationDrop.ts";
import type { Synthesis } from "../main/events/other/Synthesis.ts";
import type { SystemsShutdown } from "../main/events/other/SystemsShutdown.ts";
import type { USSDrop } from "../main/events/other/USSDrop.ts";
import type { VehicleSwitch } from "../main/events/other/VehicleSwitch.ts";
import type { WingAdd } from "../main/events/other/WingAdd.ts";
import type { WingInvite } from "../main/events/other/WingInvite.ts";
import type { WingJoin } from "../main/events/other/WingJoin.ts";
import type { WingLeave } from "../main/events/other/WingLeave.ts";
import type { DeliverPowerMicroResources } from "../main/events/powerplay/DeliverPowerMicroResources.ts";
import type { PowerplayCollect } from "../main/events/powerplay/PowerplayCollect.ts";
import type { PowerplayDefect } from "../main/events/powerplay/PowerplayDefect.ts";
import type { PowerplayDeliver } from "../main/events/powerplay/PowerplayDeliver.ts";
import type { PowerplayFastTrack } from "../main/events/powerplay/PowerplayFastTrack.ts";
import type { PowerplayJoin } from "../main/events/powerplay/PowerplayJoin.ts";
import type { PowerplayLeave } from "../main/events/powerplay/PowerplayLeave.ts";
import type { PowerplayMerits } from "../main/events/powerplay/PowerplayMerits.ts";
import type { PowerplayRank } from "../main/events/powerplay/PowerplayRank.ts";
import type { PowerplaySalary } from "../main/events/powerplay/PowerplaySalary.ts";
import type { PowerplayVote } from "../main/events/powerplay/PowerplayVote.ts";
import type { PowerplayVoucher } from "../main/events/powerplay/PowerplayVoucher.ts";
import type { AppliedToSquadron } from "../main/events/squadrons/AppliedToSquadron.ts";
import type { InvitedToSquadron } from "../main/events/squadrons/InvitedToSquadron.ts";
import type { JoinedSquadron } from "../main/events/squadrons/JoinedSquadron.ts";
import type { LeftSquadron } from "../main/events/squadrons/LeftSquadron.ts";
import type { SharedBookmarkToSquadron } from "../main/events/squadrons/SharedBookmarkToSquadron.ts";
import type { SquadronCreated } from "../main/events/squadrons/SquadronCreated.ts";
import type { SquadronDemotion } from "../main/events/squadrons/SquadronDemotion.ts";
import type { SquadronPromotion } from "../main/events/squadrons/SquadronPromotion.ts";
import type { SquadronStartup } from "../main/events/squadrons/SquadronStartup.ts";
import type { Cargo, CargoVessel } from "../main/events/startup/Cargo.ts";
import type { ClearSavedGame } from "../main/events/startup/ClearSavedGame.ts";
import type { Commander } from "../main/events/startup/Commander.ts";
import type { Fileheader } from "../main/events/startup/Fileheader.ts";
import type { GameMode, LoadGame } from "../main/events/startup/LoadGame.ts";
import type { Loadout } from "../main/events/startup/Loadout.ts";
import type { Material, Materials } from "../main/events/startup/Materials.ts";
import type { Mission, Missions } from "../main/events/startup/Missions.ts";
import type { NewCommander } from "../main/events/startup/NewCommander.ts";
import type { Passengers } from "../main/events/startup/Passengers.ts";
import type { Powerplay } from "../main/events/startup/Powerplay.ts";
import type { Progress } from "../main/events/startup/Progress.ts";
import type { Rank } from "../main/events/startup/Rank.ts";
import type { Reputation } from "../main/events/startup/Reputation.ts";
import type { Statistics } from "../main/events/startup/Statistics.ts";
import type { BuyAmmo } from "../main/events/station/BuyAmmo.ts";
import type { BuyDrones } from "../main/events/station/BuyDrones.ts";
import type { CargoDepot } from "../main/events/station/CargoDepot.ts";
import type { CommunityGoal } from "../main/events/station/CommunityGoal.ts";
import type { CommunityGoalDiscard } from "../main/events/station/CommunityGoalDiscard.ts";
import type { CommunityGoalJoin } from "../main/events/station/CommunityGoalJoin.ts";
import type { CommunityGoalReward } from "../main/events/station/CommunityGoalReward.ts";
import type { CrewAssign } from "../main/events/station/CrewAssign.ts";
import type { CrewFire } from "../main/events/station/CrewFire.ts";
import type { CrewHire } from "../main/events/station/CrewHire.ts";
import type { EngineerApply } from "../main/events/station/EngineerApply.ts";
import type { EngineerContribution } from "../main/events/station/EngineerContribution.ts";
import type { EngineerCraft } from "../main/events/station/EngineerCraft.ts";
import type { EngineerLegacyConvert } from "../main/events/station/EngineerLegacyConvert.ts";
import type {
    Engineer, EngineerBase, EngineerProgress, EngineerProgressState, LockedEngineer, UnlockedEngineer
} from "../main/events/station/EngineerProgress.js";
import type { FetchRemoteModule } from "../main/events/station/FetchRemoteModule.ts";
import type { ExtendedMarket, Market } from "../main/events/station/Market.ts";
import type { MassModuleStore } from "../main/events/station/MassModuleStore.ts";
import type { MaterialTrade } from "../main/events/station/MaterialTrade.ts";
import type { MissionAbandoned } from "../main/events/station/MissionAbandoned.ts";
import type { MissionAccepted } from "../main/events/station/MissionAccepted.ts";
import type { MissionCompleted } from "../main/events/station/MissionCompleted.ts";
import type { MissionFailed } from "../main/events/station/MissionFailed.ts";
import type { MissionRedirected } from "../main/events/station/MissionRedirected.ts";
import type { ModuleBuy } from "../main/events/station/ModuleBuy.ts";
import type { ModuleBuyAndStore } from "../main/events/station/ModuleBuyAndStore.ts";
import type { ModuleRetrieve } from "../main/events/station/ModuleRetrieve.ts";
import type { ModuleSell } from "../main/events/station/ModuleSell.ts";
import type { ModuleSellRemote } from "../main/events/station/ModuleSellRemote.ts";
import type { ModuleStore } from "../main/events/station/ModuleStore.ts";
import type { ModuleSwap } from "../main/events/station/ModuleSwap.ts";
import type { ExtendedOutfitting, Outfitting } from "../main/events/station/Outfitting.ts";
import type { PayBounties } from "../main/events/station/PayBounties.ts";
import type { PayFines } from "../main/events/station/PayFines.ts";
import type { PayLegacyFines } from "../main/events/station/PayLegacyFines.ts";
import type { RedeemVoucher } from "../main/events/station/RedeemVoucher.ts";
import type { RefuelAll } from "../main/events/station/RefuelAll.ts";
import type { RefuelPartial } from "../main/events/station/RefuelPartial.ts";
import type { Repair } from "../main/events/station/Repair.ts";
import type { RepairAll } from "../main/events/station/RepairAll.ts";
import type { RestockVehicle } from "../main/events/station/RestockVehicle.ts";
import type { ScientificResearch } from "../main/events/station/ScientificResearch.ts";
import type { SearchAndRescue } from "../main/events/station/SearchAndRescue.ts";
import type { SellDrones } from "../main/events/station/SellDrones.ts";
import type { SellShipOnRebuy } from "../main/events/station/SellShipOnRebuy.ts";
import type { SetUserShipName } from "../main/events/station/SetUserShipName.ts";
import type { ShipRedeemed } from "../main/events/station/ShipRedeemed.ts";
import type { ExtendedShipyard, Shipyard } from "../main/events/station/Shipyard.ts";
import type { ShipyardBankDeposit } from "../main/events/station/ShipyardBankDeposit.ts";
import type { ShipyardBuy } from "../main/events/station/ShipyardBuy.ts";
import type { ShipyardNew } from "../main/events/station/ShipyardNew.ts";
import type { ShipyardRedeem } from "../main/events/station/ShipyardRedeem.ts";
import type { ShipyardSell } from "../main/events/station/ShipyardSell.ts";
import type { ShipyardSwap } from "../main/events/station/ShipyardSwap.ts";
import type { ShipyardTransfer } from "../main/events/station/ShipyardTransfer.ts";
import type { StoredModules } from "../main/events/station/StoredModules.ts";
import type { StoredShips } from "../main/events/station/StoredShips.ts";
import type { TechnologyBroker } from "../main/events/station/TechnologyBroker.ts";
import type { AsteroidCracked } from "../main/events/trade/AsteroidCracked.ts";
import type { BuyTradeData } from "../main/events/trade/BuyTradeData.ts";
import type { CollectCargo } from "../main/events/trade/CollectCargo.ts";
import type { EjectCargo } from "../main/events/trade/EjectCargo.ts";
import type { MarketBuy } from "../main/events/trade/MarketBuy.ts";
import type { MarketSell } from "../main/events/trade/MarketSell.ts";
import type { MiningRefined } from "../main/events/trade/MiningRefined.ts";
import type { ApproachBody } from "../main/events/travel/ApproachBody.ts";
import type { Docked } from "../main/events/travel/Docked.ts";
import type { DockingCancelled } from "../main/events/travel/DockingCancelled.ts";
import type { DockingDenied } from "../main/events/travel/DockingDenied.ts";
import type { DockingGranted } from "../main/events/travel/DockingGranted.ts";
import type { DockingRequested } from "../main/events/travel/DockingRequested.ts";
import type { DockingTimeout } from "../main/events/travel/DockingTimeout.ts";
import type { FSDJump } from "../main/events/travel/FSDJump.ts";
import type { FSDTarget } from "../main/events/travel/FSDTarget.ts";
import type { LeaveBody } from "../main/events/travel/LeaveBody.ts";
import type { Liftoff } from "../main/events/travel/Liftoff.ts";
import type { Location } from "../main/events/travel/Location.ts";
import type { ExtendedNavRoute, NavRoute } from "../main/events/travel/NavRoute.ts";
import type { NavRouteClear } from "../main/events/travel/NavRouteClear.ts";
import type { JumpType, StartJump } from "../main/events/travel/StartJump.ts";
import type { SupercruiseEntry } from "../main/events/travel/SupercruiseEntry.ts";
import type { SupercruiseExit } from "../main/events/travel/SupercruiseExit.ts";
import type { Touchdown } from "../main/events/travel/Touchdown.ts";
import type { Undocked } from "../main/events/travel/Undocked.ts";
import type { BodyType } from "../main/events/types/BodyType.ts";
import type { CarrierType } from "../main/events/types/CarrierType.ts";
import type { ConflictFaction } from "../main/events/types/ConflictFaction.ts";
import type { ConflictProgress } from "../main/events/types/ConflictProgress.ts";
import type { ID } from "../main/events/types/ID.ts";
import type { MicroResource } from "../main/events/types/MicroResource.ts";
import type { PlanetClass } from "../main/events/types/PlanetClass.ts";
import type { PowerState, PowerState1, PowerState2 } from "../main/events/types/PowerState.ts";
import type { StarType } from "../main/events/types/StarType.ts";
import type { StationService } from "../main/events/types/StationService.ts";
import type { StationType } from "../main/events/types/StationType.ts";
import * as exports from "../main/index.ts";
import { Journal, type JournalOptions } from "../main/Journal.ts";
import { JournalError } from "../main/JournalError.ts";
import type { JournalEvent } from "../main/JournalEvent.ts";
import type { JournalPosition, NamedJournalPosition } from "../main/JournalPosition.ts";
import { assertEquals } from "@kayahr/assert";

describe("core", () => {
    it("exports relevant types and functions and nothing else", () => {
        assertEquals({ ...exports }, {
            Journal,
            JournalError
        });

        // Interfaces and types can only be checked by TypeScript
        ((): JournalOptions => (({} as exports.JournalOptions)))();
        ((): JournalEvent => (({} as exports.JournalEvent)))();
        ((): JournalPosition => (({} as exports.JournalPosition)))();
        ((): NamedJournalPosition => (({} as exports.NamedJournalPosition)))();
        ((): EjectCargo => (({} as exports.EjectCargo)))();
        ((): MarketBuy => (({} as exports.MarketBuy)))();
        ((): AsteroidCracked => (({} as exports.AsteroidCracked)))();
        ((): BuyTradeData => (({} as exports.BuyTradeData)))();
        ((): CollectCargo => (({} as exports.CollectCargo)))();
        ((): MarketSell => (({} as exports.MarketSell)))();
        ((): MiningRefined => (({} as exports.MiningRefined)))();
        ((): Interdiction => (({} as exports.Interdiction)))();
        ((): HeatWarning => (({} as exports.HeatWarning)))();
        ((): UnderAttack => (({} as exports.UnderAttack)))();
        ((): PVPKill => (({} as exports.PVPKill)))();
        ((): FactionKillBond => (({} as exports.FactionKillBond)))();
        ((): FighterDestroyed => (({} as exports.FighterDestroyed)))();
        ((): Interdicted => (({} as exports.Interdicted)))();
        ((): Died => (({} as exports.Died)))();
        ((): HeatDamage => (({} as exports.HeatDamage)))();
        ((): Bounty => (({} as exports.Bounty)))();
        ((): ShipTargeted => (({} as exports.ShipTargeted)))();
        ((): CapShipBond => (({} as exports.CapShipBond)))();
        ((): ShieldState => (({} as exports.ShieldState)))();
        ((): SRVDestroyed => (({} as exports.SRVDestroyed)))();
        ((): EscapeInterdiction => (({} as exports.EscapeInterdiction)))();
        ((): HullDamage => (({} as exports.HullDamage)))();
        ((): ConflictFaction => (({} as exports.ConflictFaction)))();
        ((): PowerState => (({} as exports.PowerState)))();
        ((): PowerState1 => (({} as exports.PowerState1)))();
        ((): PowerState2 => (({} as exports.PowerState2)))();
        ((): BodyType => (({} as exports.BodyType)))();
        ((): StationType => (({} as exports.StationType)))();
        ((): CarrierType => (({} as exports.CarrierType)))();
        ((): MicroResource => (({} as exports.MicroResource)))();
        ((): StationService => (({} as exports.StationService)))();
        ((): ConflictProgress => (({} as exports.ConflictProgress)))();
        ((): ID => (({} as exports.ID)))();
        ((): SupercruiseExit => (({} as exports.SupercruiseExit)))();
        ((): Liftoff => (({} as exports.Liftoff)))();
        ((): ExtendedNavRoute => (({} as exports.ExtendedNavRoute)))();
        ((): NavRoute => (({} as exports.NavRoute)))();
        ((): DockingGranted => (({} as exports.DockingGranted)))();
        ((): Docked => (({} as exports.Docked)))();
        ((): NavRouteClear => (({} as exports.NavRouteClear)))();
        ((): Undocked => (({} as exports.Undocked)))();
        ((): Touchdown => (({} as exports.Touchdown)))();
        ((): DockingRequested => (({} as exports.DockingRequested)))();
        ((): ApproachBody => (({} as exports.ApproachBody)))();
        ((): DockingDenied => (({} as exports.DockingDenied)))();
        ((): LeaveBody => (({} as exports.LeaveBody)))();
        ((): DockingTimeout => (({} as exports.DockingTimeout)))();
        ((): SupercruiseEntry => (({} as exports.SupercruiseEntry)))();
        ((): FSDJump => (({} as exports.FSDJump)))();
        ((): FSDTarget => (({} as exports.FSDTarget)))();
        ((): DockingCancelled => (({} as exports.DockingCancelled)))();
        ((): Location => (({} as exports.Location)))();
        ((): JumpType => (({} as exports.JumpType)))();
        ((): StartJump => (({} as exports.StartJump)))();
        ((): NewCommander => (({} as exports.NewCommander)))();
        ((): Cargo => (({} as exports.Cargo)))();
        ((): CargoVessel => (({} as exports.CargoVessel)))();
        ((): Rank => (({} as exports.Rank)))();
        ((): Statistics => (({} as exports.Statistics)))();
        ((): Fileheader => (({} as exports.Fileheader)))();
        ((): Powerplay => (({} as exports.Powerplay)))();
        ((): Loadout => (({} as exports.Loadout)))();
        ((): Material => (({} as exports.Material)))();
        ((): Materials => (({} as exports.Materials)))();
        ((): Mission => (({} as exports.Mission)))();
        ((): Missions => (({} as exports.Missions)))();
        ((): Reputation => (({} as exports.Reputation)))();
        ((): Commander => (({} as exports.Commander)))();
        ((): ClearSavedGame => (({} as exports.ClearSavedGame)))();
        ((): GameMode => (({} as exports.GameMode)))();
        ((): LoadGame => (({} as exports.LoadGame)))();
        ((): Progress => (({} as exports.Progress)))();
        ((): Passengers => (({} as exports.Passengers)))();
        ((): SharedBookmarkToSquadron => (({} as exports.SharedBookmarkToSquadron)))();
        ((): LeftSquadron => (({} as exports.LeftSquadron)))();
        ((): SquadronPromotion => (({} as exports.SquadronPromotion)))();
        ((): SquadronDemotion => (({} as exports.SquadronDemotion)))();
        ((): SquadronStartup => (({} as exports.SquadronStartup)))();
        ((): JoinedSquadron => (({} as exports.JoinedSquadron)))();
        ((): AppliedToSquadron => (({} as exports.AppliedToSquadron)))();
        ((): SquadronCreated => (({} as exports.SquadronCreated)))();
        ((): InvitedToSquadron => (({} as exports.InvitedToSquadron)))();
        ((): DataScanned => (({} as exports.DataScanned)))();
        ((): SelfDestruct => (({} as exports.SelfDestruct)))();
        ((): Friends => (({} as exports.Friends)))();
        ((): USSDrop => (({} as exports.USSDrop)))();
        ((): LaunchSRV => (({} as exports.LaunchSRV)))();
        ((): CrewMemberQuits => (({} as exports.CrewMemberQuits)))();
        ((): WingInvite => (({} as exports.WingInvite)))();
        ((): CrimeVictim => (({} as exports.CrimeVictim)))();
        ((): JoinACrew => (({} as exports.JoinACrew)))();
        ((): Continued => (({} as exports.Continued)))();
        ((): RepairDrone => (({} as exports.RepairDrone)))();
        ((): FighterRebuilt => (({} as exports.FighterRebuilt)))();
        ((): LaunchFighter => (({} as exports.LaunchFighter)))();
        ((): ReceiveText => (({} as exports.ReceiveText)))();
        ((): ExtendedModuleInfo => (({} as exports.ExtendedModuleInfo)))();
        ((): ModuleInfo => (({} as exports.ModuleInfo)))();
        ((): DockFighter => (({} as exports.DockFighter)))();
        ((): CargoTransfer => (({} as exports.CargoTransfer)))();
        ((): FuelScoop => (({} as exports.FuelScoop)))();
        ((): CockpitBreached => (({} as exports.CockpitBreached)))();
        ((): ColonisationConstructionDepot => (({} as exports.ColonisationConstructionDepot)))();
        ((): ColonisationConstructionResource => (({} as exports.ColonisationConstructionResource)))();
        ((): ColonisationContribution => (({} as exports.ColonisationContribution)))();
        ((): ColonisationContributionResource => (({} as exports.ColonisationContributionResource)))();
        ((): ProspectedAsteroid => (({} as exports.ProspectedAsteroid)))();
        ((): Shutdown => (({} as exports.Shutdown)))();
        ((): SendText => (({} as exports.SendText)))();
        ((): ReservoirReplenished => (({} as exports.ReservoirReplenished)))();
        ((): Resupply => (({} as exports.Resupply)))();
        ((): VehicleSwitch => (({} as exports.VehicleSwitch)))();
        ((): Scanned => (({} as exports.Scanned)))();
        ((): RebootRepair => (({} as exports.RebootRepair)))();
        ((): Resurrect => (({} as exports.Resurrect)))();
        ((): DatalinkScan => (({} as exports.DatalinkScan)))();
        ((): KickCrewMember => (({} as exports.KickCrewMember)))();
        ((): DockSRV => (({} as exports.DockSRV)))();
        ((): AfmuRepairs => (({} as exports.AfmuRepairs)))();
        ((): WingAdd => (({} as exports.WingAdd)))();
        ((): CrewMemberJoins => (({} as exports.CrewMemberJoins)))();
        ((): SystemsShutdown => (({} as exports.SystemsShutdown)))();
        ((): Promotion => (({} as exports.Promotion)))();
        ((): CommitCrime => (({} as exports.CommitCrime)))();
        ((): LegalState => (({} as exports.LegalState)))();
        ((): Status => (({} as exports.Status)))();
        ((): JetConeDamage => (({} as exports.JetConeDamage)))();
        ((): DatalinkVoucher => (({} as exports.DatalinkVoucher)))();
        ((): Synthesis => (({} as exports.Synthesis)))();
        ((): CrewMemberRoleChange => (({} as exports.CrewMemberRoleChange)))();
        ((): JetConeBoost => (({} as exports.JetConeBoost)))();
        ((): ApproachSettlement => (({} as exports.ApproachSettlement)))();
        ((): EndCrewSession => (({} as exports.EndCrewSession)))();
        ((): WingLeave => (({} as exports.WingLeave)))();
        ((): WingJoin => (({} as exports.WingJoin)))();
        ((): CrewLaunchFighter => (({} as exports.CrewLaunchFighter)))();
        ((): SupercruiseDestinationDrop => (({} as exports.SupercruiseDestinationDrop)))();
        ((): NpcCrewPaidWage => (({} as exports.NpcCrewPaidWage)))();
        ((): QuitACrew => (({} as exports.QuitACrew)))();
        ((): LaunchDrone => (({} as exports.LaunchDrone)))();
        ((): NpcCrewRank => (({} as exports.NpcCrewRank)))();
        ((): ChangeCrewRole => (({} as exports.ChangeCrewRole)))();
        ((): Music => (({} as exports.Music)))();
        ((): CodexEntry => (({} as exports.CodexEntry)))();
        ((): SAAScanComplete => (({} as exports.SAAScanComplete)))();
        ((): PlanetClass => (({} as exports.PlanetClass)))();
        ((): ReserveLevel => (({} as exports.ReserveLevel)))();
        ((): Ring => (({} as exports.Ring)))();
        ((): RingClass => (({} as exports.RingClass)))();
        ((): ScanOther => (({} as exports.ScanOther)))();
        ((): ScanPlanet => (({} as exports.ScanPlanet)))();
        ((): ScanStar => (({} as exports.ScanStar)))();
        ((): Scan => (({} as exports.Scan)))();
        ((): ScanType => (({} as exports.ScanType)))();
        ((): StarType => (({} as exports.StarType)))();
        ((): FSSSignalDiscovered => (({} as exports.FSSSignalDiscovered)))();
        ((): SignalType => (({} as exports.SignalType)))();
        ((): BuyExplorationData => (({} as exports.BuyExplorationData)))();
        ((): Screenshot => (({} as exports.Screenshot)))();
        ((): MaterialDiscovered => (({} as exports.MaterialDiscovered)))();
        ((): NavBeaconScan => (({} as exports.NavBeaconScan)))();
        ((): MaterialCollected => (({} as exports.MaterialCollected)))();
        ((): SellExplorationData => (({} as exports.SellExplorationData)))();
        ((): SAASignalsFound => (({} as exports.SAASignalsFound)))();
        ((): ScanBaryCentre => (({} as exports.ScanBaryCentre)))();
        ((): DiscoveryScan => (({} as exports.DiscoveryScan)))();
        ((): FSSAllBodiesFound => (({} as exports.FSSAllBodiesFound)))();
        ((): FSSBodySignals => (({} as exports.FSSBodySignals)))();
        ((): MaterialDiscarded => (({} as exports.MaterialDiscarded)))();
        ((): MultiSellExplorationData => (({} as exports.MultiSellExplorationData)))();
        ((): FSSDiscoveryScan => (({} as exports.FSSDiscoveryScan)))();
        ((): CarrierNameChange => (({} as exports.CarrierNameChange)))();
        ((): CarrierDockingPermission => (({} as exports.CarrierDockingPermission)))();
        ((): CarrierJumpCancelled => (({} as exports.CarrierJumpCancelled)))();
        ((): CarrierBankTransfer => (({} as exports.CarrierBankTransfer)))();
        ((): CarrierCrewServices => (({} as exports.CarrierCrewServices)))();
        ((): CarrierFinance => (({} as exports.CarrierFinance)))();
        ((): CarrierLocation => (({} as exports.CarrierLocation)))();
        ((): CarrierTradeOrder => (({} as exports.CarrierTradeOrder)))();
        ((): CarrierModulePack => (({} as exports.CarrierModulePack)))();
        ((): CarrierModulePackBase => (({} as exports.CarrierModulePackBase)))();
        ((): CarrierModulePackBuy => (({} as exports.CarrierModulePackBuy)))();
        ((): CarrierModulePackSell => (({} as exports.CarrierModulePackSell)))();
        ((): CarrierDepositFuel => (({} as exports.CarrierDepositFuel)))();
        ((): CarrierJumpRequest => (({} as exports.CarrierJumpRequest)))();
        ((): CarrierShipPack => (({} as exports.CarrierShipPack)))();
        ((): CarrierShipPackBase => (({} as exports.CarrierShipPackBase)))();
        ((): CarrierShipPackBuy => (({} as exports.CarrierShipPackBuy)))();
        ((): CarrierShipPackSell => (({} as exports.CarrierShipPackSell)))();
        ((): CarrierJump => (({} as exports.CarrierJump)))();
        ((): CarrierBuy => (({} as exports.CarrierBuy)))();
        ((): CarrierStats => (({} as exports.CarrierStats)))();
        ((): Pack => (({} as exports.Pack)))();
        ((): PowerplayJoin => (({} as exports.PowerplayJoin)))();
        ((): PowerplayVote => (({} as exports.PowerplayVote)))();
        ((): DeliverPowerMicroResources => (({} as exports.DeliverPowerMicroResources)))();
        ((): PowerplaySalary => (({} as exports.PowerplaySalary)))();
        ((): PowerplayVoucher => (({} as exports.PowerplayVoucher)))();
        ((): PowerplayMerits => (({} as exports.PowerplayMerits)))();
        ((): PowerplayRank => (({} as exports.PowerplayRank)))();
        ((): PowerplayFastTrack => (({} as exports.PowerplayFastTrack)))();
        ((): PowerplayDeliver => (({} as exports.PowerplayDeliver)))();
        ((): PowerplayLeave => (({} as exports.PowerplayLeave)))();
        ((): PowerplayCollect => (({} as exports.PowerplayCollect)))();
        ((): PowerplayDefect => (({} as exports.PowerplayDefect)))();
        ((): ModuleStore => (({} as exports.ModuleStore)))();
        ((): MassModuleStore => (({} as exports.MassModuleStore)))();
        ((): MissionCompleted => (({} as exports.MissionCompleted)))();
        ((): MissionFailed => (({} as exports.MissionFailed)))();
        ((): StoredModules => (({} as exports.StoredModules)))();
        ((): CommunityGoalDiscard => (({} as exports.CommunityGoalDiscard)))();
        ((): ShipyardTransfer => (({} as exports.ShipyardTransfer)))();
        ((): ModuleRetrieve => (({} as exports.ModuleRetrieve)))();
        ((): ShipyardSwap => (({} as exports.ShipyardSwap)))();
        ((): Repair => (({} as exports.Repair)))();
        ((): CrewFire => (({} as exports.CrewFire)))();
        ((): SellShipOnRebuy => (({} as exports.SellShipOnRebuy)))();
        ((): ExtendedMarket => (({} as exports.ExtendedMarket)))();
        ((): Market => (({} as exports.Market)))();
        ((): CommunityGoalJoin => (({} as exports.CommunityGoalJoin)))();
        ((): Engineer => (({} as exports.Engineer)))();
        ((): EngineerBase => (({} as exports.EngineerBase)))();
        ((): EngineerProgress => (({} as exports.EngineerProgress)))();
        ((): EngineerProgressState => (({} as exports.EngineerProgressState)))();
        ((): LockedEngineer => (({} as exports.LockedEngineer)))();
        ((): UnlockedEngineer => (({} as exports.UnlockedEngineer)))();
        ((): PayBounties => (({} as exports.PayBounties)))();
        ((): ShipyardBankDeposit => (({} as exports.ShipyardBankDeposit)))();
        ((): ShipyardRedeem => (({} as exports.ShipyardRedeem)))();
        ((): ShipyardSell => (({} as exports.ShipyardSell)))();
        ((): MissionAbandoned => (({} as exports.MissionAbandoned)))();
        ((): RefuelPartial => (({} as exports.RefuelPartial)))();
        ((): EngineerContribution => (({} as exports.EngineerContribution)))();
        ((): PayFines => (({} as exports.PayFines)))();
        ((): CargoDepot => (({} as exports.CargoDepot)))();
        ((): BuyAmmo => (({} as exports.BuyAmmo)))();
        ((): BuyDrones => (({} as exports.BuyDrones)))();
        ((): ExtendedOutfitting => (({} as exports.ExtendedOutfitting)))();
        ((): Outfitting => (({} as exports.Outfitting)))();
        ((): ModuleBuyAndStore => (({} as exports.ModuleBuyAndStore)))();
        ((): EngineerApply => (({} as exports.EngineerApply)))();
        ((): SearchAndRescue => (({} as exports.SearchAndRescue)))();
        ((): ModuleSell => (({} as exports.ModuleSell)))();
        ((): CrewHire => (({} as exports.CrewHire)))();
        ((): ExtendedShipyard => (({} as exports.ExtendedShipyard)))();
        ((): Shipyard => (({} as exports.Shipyard)))();
        ((): RefuelAll => (({} as exports.RefuelAll)))();
        ((): MaterialTrade => (({} as exports.MaterialTrade)))();
        ((): TechnologyBroker => (({} as exports.TechnologyBroker)))();
        ((): CrewAssign => (({} as exports.CrewAssign)))();
        ((): RedeemVoucher => (({} as exports.RedeemVoucher)))();
        ((): SellDrones => (({} as exports.SellDrones)))();
        ((): ModuleSellRemote => (({} as exports.ModuleSellRemote)))();
        ((): ShipRedeemed => (({} as exports.ShipRedeemed)))();
        ((): MissionRedirected => (({} as exports.MissionRedirected)))();
        ((): ModuleSwap => (({} as exports.ModuleSwap)))();
        ((): EngineerCraft => (({} as exports.EngineerCraft)))();
        ((): ModuleBuy => (({} as exports.ModuleBuy)))();
        ((): FetchRemoteModule => (({} as exports.FetchRemoteModule)))();
        ((): RepairAll => (({} as exports.RepairAll)))();
        ((): CommunityGoal => (({} as exports.CommunityGoal)))();
        ((): SetUserShipName => (({} as exports.SetUserShipName)))();
        ((): EngineerLegacyConvert => (({} as exports.EngineerLegacyConvert)))();
        ((): ScientificResearch => (({} as exports.ScientificResearch)))();
        ((): CommunityGoalReward => (({} as exports.CommunityGoalReward)))();
        ((): StoredShips => (({} as exports.StoredShips)))();
        ((): MissionAccepted => (({} as exports.MissionAccepted)))();
        ((): ShipyardNew => (({} as exports.ShipyardNew)))();
        ((): ShipyardBuy => (({} as exports.ShipyardBuy)))();
        ((): RestockVehicle => (({} as exports.RestockVehicle)))();
        ((): PayLegacyFines => (({} as exports.PayLegacyFines)))();
        ((): CreateSuitLoadout => (({} as exports.CreateSuitLoadout)))();
        ((): SellMicroResources => (({} as exports.SellMicroResources)))();
        ((): DropItems => (({} as exports.DropItems)))();
        ((): Disembark => (({} as exports.Disembark)))();
        ((): BookDropship => (({} as exports.BookDropship)))();
        ((): UseConsumable => (({} as exports.UseConsumable)))();
        ((): BuyWeapon => (({} as exports.BuyWeapon)))();
        ((): TradeMicroResources => (({} as exports.TradeMicroResources)))();
        ((): UpgradeWeapon => (({} as exports.UpgradeWeapon)))();
        ((): RenameSuitLoadout => (({} as exports.RenameSuitLoadout)))();
        ((): ExtendedFCMaterials => (({} as exports.ExtendedFCMaterials)))();
        ((): FCMaterials => (({} as exports.FCMaterials)))();
        ((): SellWeapon => (({} as exports.SellWeapon)))();
        ((): CollectItems => (({} as exports.CollectItems)))();
        ((): LoadoutEquipModule => (({} as exports.LoadoutEquipModule)))();
        ((): ScanOrganic => (({} as exports.ScanOrganic)))();
        ((): UpgradeSuit => (({} as exports.UpgradeSuit)))();
        ((): BackpackChange => (({} as exports.BackpackChange)))();
        ((): ChangedBackpackItem => (({} as exports.ChangedBackpackItem)))();
        ((): SellSuit => (({} as exports.SellSuit)))();
        ((): SwitchSuitLoadout => (({} as exports.SwitchSuitLoadout)))();
        ((): Embark => (({} as exports.Embark)))();
        ((): BuySuit => (({} as exports.BuySuit)))();
        ((): BookTaxi => (({} as exports.BookTaxi)))();
        ((): CancelTaxi => (({} as exports.CancelTaxi)))();
        ((): CancelDropship => (({} as exports.CancelDropship)))();
        ((): TransferMicroResources => (({} as exports.TransferMicroResources)))();
        ((): SuitLoadout => (({} as exports.SuitLoadout)))();
        ((): DeleteSuitLoadout => (({} as exports.DeleteSuitLoadout)))();
        ((): Backpack => (({} as exports.Backpack)))();
        ((): BackpackItem => (({} as exports.BackpackItem)))();
        ((): DropshipDeploy => (({} as exports.DropshipDeploy)))();
        ((): BuyMicroResources => (({} as exports.BuyMicroResources)))();
        ((): OldBuyMicroResources => (({} as exports.OldBuyMicroResources)))();
        ((): NewBuyMicroResources => (({} as exports.NewBuyMicroResources)))();
        ((): SellOrganicData => (({} as exports.SellOrganicData)))();
        ((): ShipLocker => (({} as exports.ShipLocker)))();
        ((): ShipLockerItem => (({} as exports.ShipLockerItem)))();
    });
});
