import { describe, expect, it } from "vitest";

import type { CarrierBankTransfer } from "../main/events/carrier/CarrierBankTransfer.js";
import type { CarrierBuy } from "../main/events/carrier/CarrierBuy.js";
import type { CarrierCrewServices } from "../main/events/carrier/CarrierCrewServices.js";
import type { CarrierDepositFuel } from "../main/events/carrier/CarrierDepositFuel.js";
import type { CarrierDockingPermission } from "../main/events/carrier/CarrierDockingPermission.js";
import type { CarrierFinance } from "../main/events/carrier/CarrierFinance.js";
import type { CarrierJump } from "../main/events/carrier/CarrierJump.js";
import type { CarrierJumpCancelled } from "../main/events/carrier/CarrierJumpCancelled.js";
import type { CarrierJumpRequest } from "../main/events/carrier/CarrierJumpRequest.js";
import type { CarrierLocation } from "../main/events/carrier/CarrierLocation.js";
import type { CarrierModulePack, CarrierModulePackBase, CarrierModulePackBuy, CarrierModulePackSell } from "../main/events/carrier/CarrierModulePack.js";
import type { CarrierNameChange } from "../main/events/carrier/CarrierNameChange.js";
import type { CarrierShipPack, CarrierShipPackBase, CarrierShipPackBuy, CarrierShipPackSell } from "../main/events/carrier/CarrierShipPack.js";
import type { CarrierStats, Pack } from "../main/events/carrier/CarrierStats.js";
import type { CarrierTradeOrder } from "../main/events/carrier/CarrierTradeOrder.js";
import type { Bounty } from "../main/events/combat/Bounty.js";
import type { CapShipBond } from "../main/events/combat/CapShipBond.js";
import type { Died } from "../main/events/combat/Died.js";
import type { EscapeInterdiction } from "../main/events/combat/EscapeInterdiction.js";
import type { FactionKillBond } from "../main/events/combat/FactionKillBond.js";
import type { FighterDestroyed } from "../main/events/combat/FighterDestroyed.js";
import type { HeatDamage } from "../main/events/combat/HeatDamage.js";
import type { HeatWarning } from "../main/events/combat/HeatWarning.js";
import type { HullDamage } from "../main/events/combat/HullDamage.js";
import type { Interdicted } from "../main/events/combat/Interdicted.js";
import type { Interdiction } from "../main/events/combat/Interdiction.js";
import type { PVPKill } from "../main/events/combat/PVPKill.js";
import type { ShieldState } from "../main/events/combat/ShieldState.js";
import type { ShipTargeted } from "../main/events/combat/ShipTargeted.js";
import type { SRVDestroyed } from "../main/events/combat/SRVDestroyed.js";
import type { UnderAttack } from "../main/events/combat/UnderAttack.js";
import type { BuyExplorationData } from "../main/events/exploration/BuyExplorationData.js";
import type { CodexEntry } from "../main/events/exploration/CodexEntry.js";
import type { DiscoveryScan } from "../main/events/exploration/DiscoveryScan.js";
import type { FSSAllBodiesFound } from "../main/events/exploration/FSSAllBodiesFound.js";
import type { FSSBodySignals } from "../main/events/exploration/FSSBodySignals.js";
import type { FSSDiscoveryScan } from "../main/events/exploration/FSSDiscoveryScan.js";
import type { FSSSignalDiscovered, SignalType } from "../main/events/exploration/FSSSignalDiscovered.js";
import type { MaterialCollected } from "../main/events/exploration/MaterialCollected.js";
import type { MaterialDiscarded } from "../main/events/exploration/MaterialDiscarded.js";
import type { MaterialDiscovered } from "../main/events/exploration/MaterialDiscovered.js";
import type { MultiSellExplorationData } from "../main/events/exploration/MultiSellExplorationData.js";
import type { NavBeaconScan } from "../main/events/exploration/NavBeaconScan.js";
import type { SAAScanComplete } from "../main/events/exploration/SAAScanComplete.js";
import type { SAASignalsFound } from "../main/events/exploration/SAASignalsFound.js";
import type { Scan } from "../main/events/exploration/Scan.js";
import type { ScanBaryCentre } from "../main/events/exploration/ScanBaryCentre.js";
import type { Screenshot } from "../main/events/exploration/Screenshot.js";
import type { SellExplorationData } from "../main/events/exploration/SellExplorationData.js";
import type { Backpack, BackpackItem } from "../main/events/odyssey/Backpack.js";
import type { BackpackChange, ChangedBackpackItem } from "../main/events/odyssey/BackpackChange.js";
import type { BookDropship } from "../main/events/odyssey/BookDropship.js";
import type { BookTaxi } from "../main/events/odyssey/BookTaxi.js";
import type { BuyMicroResources, NewBuyMicroResources, OldBuyMicroResources } from "../main/events/odyssey/BuyMicroResources.js";
import type { BuySuit } from "../main/events/odyssey/BuySuit.js";
import type { BuyWeapon } from "../main/events/odyssey/BuyWeapon.js";
import type { CancelDropship } from "../main/events/odyssey/CancelDropship.js";
import type { CancelTaxi } from "../main/events/odyssey/CancelTaxi.js";
import type { CollectItems } from "../main/events/odyssey/CollectItems.js";
import type { CreateSuitLoadout } from "../main/events/odyssey/CreateSuitLoadout.js";
import type { DeleteSuitLoadout } from "../main/events/odyssey/DeleteSuitLoadout.js";
import type { Disembark } from "../main/events/odyssey/Disembark.js";
import type { DropItems } from "../main/events/odyssey/DropItems.js";
import type { DropshipDeploy } from "../main/events/odyssey/DropshipDeploy.js";
import type { Embark } from "../main/events/odyssey/Embark.js";
import type { ExtendedFCMaterials, FCMaterials } from "../main/events/odyssey/FCMaterials.js";
import type { LoadoutEquipModule } from "../main/events/odyssey/LoadoutEquipModule.js";
import type { RenameSuitLoadout } from "../main/events/odyssey/RenameSuitLoadout.js";
import type { ScanOrganic } from "../main/events/odyssey/ScanOrganic.js";
import type { SellMicroResources } from "../main/events/odyssey/SellMicroResources.js";
import type { SellOrganicData } from "../main/events/odyssey/SellOrganicData.js";
import type { SellSuit } from "../main/events/odyssey/SellSuit.js";
import type { SellWeapon } from "../main/events/odyssey/SellWeapon.js";
import type { ShipLocker, ShipLockerItem } from "../main/events/odyssey/ShipLocker.js";
import type { SuitLoadout } from "../main/events/odyssey/SuitLoadout.js";
import type { SwitchSuitLoadout } from "../main/events/odyssey/SwitchSuitLoadout.js";
import type { TradeMicroResources } from "../main/events/odyssey/TradeMicroResources.js";
import type { TransferMicroResources } from "../main/events/odyssey/TransferMicroResources.js";
import type { UpgradeSuit } from "../main/events/odyssey/UpgradeSuit.js";
import type { UpgradeWeapon } from "../main/events/odyssey/UpgradeWeapon.js";
import type { UseConsumable } from "../main/events/odyssey/UseConsumable.js";
import type { AfmuRepairs } from "../main/events/other/AfmuRepairs.js";
import type { ApproachSettlement } from "../main/events/other/ApproachSettlement.js";
import type { CargoTransfer } from "../main/events/other/CargoTransfer.js";
import type { ChangeCrewRole } from "../main/events/other/ChangeCrewRole.js";
import type { CockpitBreached } from "../main/events/other/CockpitBreached.js";
import type { CommitCrime } from "../main/events/other/CommitCrime.js";
import type { Continued } from "../main/events/other/Continued.js";
import type { CrewLaunchFighter } from "../main/events/other/CrewLaunchFighter.js";
import type { CrewMemberJoins } from "../main/events/other/CrewMemberJoins.js";
import type { CrewMemberQuits } from "../main/events/other/CrewMemberQuits.js";
import type { CrewMemberRoleChange } from "../main/events/other/CrewMemberRoleChange.js";
import type { CrimeVictim } from "../main/events/other/CrimeVictim.js";
import type { DatalinkScan } from "../main/events/other/DatalinkScan.js";
import type { DatalinkVoucher } from "../main/events/other/DatalinkVoucher.js";
import type { DataScanned } from "../main/events/other/DataScanned.js";
import type { DockFighter } from "../main/events/other/DockFighter.js";
import type { DockSRV } from "../main/events/other/DockSRV.js";
import type { EndCrewSession } from "../main/events/other/EndCrewSession.js";
import type { FighterRebuilt } from "../main/events/other/FighterRebuilt.js";
import type { Friends } from "../main/events/other/Friends.js";
import type { FuelScoop } from "../main/events/other/FuelScoop.js";
import type { JetConeBoost } from "../main/events/other/JetConeBoost.js";
import type { JetConeDamage } from "../main/events/other/JetConeDamage.js";
import type { JoinACrew } from "../main/events/other/JoinACrew.js";
import type { KickCrewMember } from "../main/events/other/KickCrewMember.js";
import type { LaunchDrone } from "../main/events/other/LaunchDrone.js";
import type { LaunchFighter } from "../main/events/other/LaunchFighter.js";
import type { LaunchSRV } from "../main/events/other/LaunchSRV.js";
import type { ExtendedModuleInfo, ModuleInfo } from "../main/events/other/ModuleInfo.js";
import type { Music } from "../main/events/other/Music.js";
import type { NpcCrewPaidWage } from "../main/events/other/NpcCrewPaidWage.js";
import type { NpcCrewRank } from "../main/events/other/NpcCrewRank.js";
import type { Promotion } from "../main/events/other/Promotion.js";
import type { ProspectedAsteroid } from "../main/events/other/ProspectedAsteroid.js";
import type { QuitACrew } from "../main/events/other/QuitACrew.js";
import type { RebootRepair } from "../main/events/other/RebootRepair.js";
import type { ReceiveText } from "../main/events/other/ReceiveText.js";
import type { RepairDrone } from "../main/events/other/RepairDrone.js";
import type { ReservoirReplenished } from "../main/events/other/ReservoirReplenished.js";
import type { Resupply } from "../main/events/other/Resupply.js";
import type { Resurrect } from "../main/events/other/Resurrect.js";
import type { Scanned } from "../main/events/other/Scanned.js";
import type { SelfDestruct } from "../main/events/other/SelfDestruct.js";
import type { SendText } from "../main/events/other/SendText.js";
import type { Shutdown } from "../main/events/other/Shutdown.js";
import type { LegalState, Status } from "../main/events/other/Status.js";
import type { SupercruiseDestinationDrop } from "../main/events/other/SupercruiseDestinationDrop.js";
import type { Synthesis } from "../main/events/other/Synthesis.js";
import type { SystemsShutdown } from "../main/events/other/SystemsShutdown.js";
import type { USSDrop } from "../main/events/other/USSDrop.js";
import type { VehicleSwitch } from "../main/events/other/VehicleSwitch.js";
import type { WingAdd } from "../main/events/other/WingAdd.js";
import type { WingInvite } from "../main/events/other/WingInvite.js";
import type { WingJoin } from "../main/events/other/WingJoin.js";
import type { WingLeave } from "../main/events/other/WingLeave.js";
import type { DeliverPowerMicroResources } from "../main/events/powerplay/DeliverPowerMicroResources.js";
import type { PowerplayCollect } from "../main/events/powerplay/PowerplayCollect.js";
import type { PowerplayDefect } from "../main/events/powerplay/PowerplayDefect.js";
import type { PowerplayDeliver } from "../main/events/powerplay/PowerplayDeliver.js";
import type { PowerplayFastTrack } from "../main/events/powerplay/PowerplayFastTrack.js";
import type { PowerplayJoin } from "../main/events/powerplay/PowerplayJoin.js";
import type { PowerplayLeave } from "../main/events/powerplay/PowerplayLeave.js";
import type { PowerplayMerits } from "../main/events/powerplay/PowerplayMerits.js";
import type { PowerplayRank } from "../main/events/powerplay/PowerplayRank.js";
import type { PowerplaySalary } from "../main/events/powerplay/PowerplaySalary.js";
import type { PowerplayVote } from "../main/events/powerplay/PowerplayVote.js";
import type { PowerplayVoucher } from "../main/events/powerplay/PowerplayVoucher.js";
import type { AppliedToSquadron } from "../main/events/squadrons/AppliedToSquadron.js";
import type { InvitedToSquadron } from "../main/events/squadrons/InvitedToSquadron.js";
import type { JoinedSquadron } from "../main/events/squadrons/JoinedSquadron.js";
import type { LeftSquadron } from "../main/events/squadrons/LeftSquadron.js";
import type { SharedBookmarkToSquadron } from "../main/events/squadrons/SharedBookmarkToSquadron.js";
import type { SquadronCreated } from "../main/events/squadrons/SquadronCreated.js";
import type { SquadronDemotion } from "../main/events/squadrons/SquadronDemotion.js";
import type { SquadronPromotion } from "../main/events/squadrons/SquadronPromotion.js";
import type { SquadronStartup } from "../main/events/squadrons/SquadronStartup.js";
import type { Cargo, CargoVessel } from "../main/events/startup/Cargo.js";
import type { ClearSavedGame } from "../main/events/startup/ClearSavedGame.js";
import type { Commander } from "../main/events/startup/Commander.js";
import type { Fileheader } from "../main/events/startup/Fileheader.js";
import type { GameMode, LoadGame } from "../main/events/startup/LoadGame.js";
import type { Loadout } from "../main/events/startup/Loadout.js";
import type { Material, Materials } from "../main/events/startup/Materials.js";
import type { Mission, Missions } from "../main/events/startup/Missions.js";
import type { NewCommander } from "../main/events/startup/NewCommander.js";
import type { Passengers } from "../main/events/startup/Passengers.js";
import type { Powerplay } from "../main/events/startup/Powerplay.js";
import type { Progress } from "../main/events/startup/Progress.js";
import type { Rank } from "../main/events/startup/Rank.js";
import type { Reputation } from "../main/events/startup/Reputation.js";
import type { Statistics } from "../main/events/startup/Statistics.js";
import type { BuyAmmo } from "../main/events/station/BuyAmmo.js";
import type { BuyDrones } from "../main/events/station/BuyDrones.js";
import type { CargoDepot } from "../main/events/station/CargoDepot.js";
import type { CommunityGoal } from "../main/events/station/CommunityGoal.js";
import type { CommunityGoalDiscard } from "../main/events/station/CommunityGoalDiscard.js";
import type { CommunityGoalJoin } from "../main/events/station/CommunityGoalJoin.js";
import type { CommunityGoalReward } from "../main/events/station/CommunityGoalReward.js";
import type { CrewAssign } from "../main/events/station/CrewAssign.js";
import type { CrewFire } from "../main/events/station/CrewFire.js";
import type { CrewHire } from "../main/events/station/CrewHire.js";
import type { EngineerApply } from "../main/events/station/EngineerApply.js";
import type { EngineerContribution } from "../main/events/station/EngineerContribution.js";
import type { EngineerCraft } from "../main/events/station/EngineerCraft.js";
import type { EngineerLegacyConvert } from "../main/events/station/EngineerLegacyConvert.js";
import type {
    Engineer, EngineerBase, EngineerProgress, EngineerProgressState, LockedEngineer, UnlockedEngineer
} from "../main/events/station/EngineerProgress.js";
import type { FetchRemoteModule } from "../main/events/station/FetchRemoteModule.js";
import type { ExtendedMarket, Market } from "../main/events/station/Market.js";
import type { MassModuleStore } from "../main/events/station/MassModuleStore.js";
import type { MaterialTrade } from "../main/events/station/MaterialTrade.js";
import type { MissionAbandoned } from "../main/events/station/MissionAbandoned.js";
import type { MissionAccepted } from "../main/events/station/MissionAccepted.js";
import type { MissionCompleted } from "../main/events/station/MissionCompleted.js";
import type { MissionFailed } from "../main/events/station/MissionFailed.js";
import type { MissionRedirected } from "../main/events/station/MissionRedirected.js";
import type { ModuleBuy } from "../main/events/station/ModuleBuy.js";
import type { ModuleBuyAndStore } from "../main/events/station/ModuleBuyAndStore.js";
import type { ModuleRetrieve } from "../main/events/station/ModuleRetrieve.js";
import type { ModuleSell } from "../main/events/station/ModuleSell.js";
import type { ModuleSellRemote } from "../main/events/station/ModuleSellRemote.js";
import type { ModuleStore } from "../main/events/station/ModuleStore.js";
import type { ModuleSwap } from "../main/events/station/ModuleSwap.js";
import type { ExtendedOutfitting, Outfitting } from "../main/events/station/Outfitting.js";
import type { PayBounties } from "../main/events/station/PayBounties.js";
import type { PayFines } from "../main/events/station/PayFines.js";
import type { PayLegacyFines } from "../main/events/station/PayLegacyFines.js";
import type { RedeemVoucher } from "../main/events/station/RedeemVoucher.js";
import type { RefuelAll } from "../main/events/station/RefuelAll.js";
import type { RefuelPartial } from "../main/events/station/RefuelPartial.js";
import type { Repair } from "../main/events/station/Repair.js";
import type { RepairAll } from "../main/events/station/RepairAll.js";
import type { RestockVehicle } from "../main/events/station/RestockVehicle.js";
import type { ScientificResearch } from "../main/events/station/ScientificResearch.js";
import type { SearchAndRescue } from "../main/events/station/SearchAndRescue.js";
import type { SellDrones } from "../main/events/station/SellDrones.js";
import type { SellShipOnRebuy } from "../main/events/station/SellShipOnRebuy.js";
import type { SetUserShipName } from "../main/events/station/SetUserShipName.js";
import type { ShipRedeemed } from "../main/events/station/ShipRedeemed.js";
import type { ExtendedShipyard, Shipyard } from "../main/events/station/Shipyard.js";
import type { ShipyardBankDeposit } from "../main/events/station/ShipyardBankDeposit.js";
import type { ShipyardBuy } from "../main/events/station/ShipyardBuy.js";
import type { ShipyardNew } from "../main/events/station/ShipyardNew.js";
import type { ShipyardRedeem } from "../main/events/station/ShipyardRedeem.js";
import type { ShipyardSell } from "../main/events/station/ShipyardSell.js";
import type { ShipyardSwap } from "../main/events/station/ShipyardSwap.js";
import type { ShipyardTransfer } from "../main/events/station/ShipyardTransfer.js";
import type { StoredModules } from "../main/events/station/StoredModules.js";
import type { StoredShips } from "../main/events/station/StoredShips.js";
import type { TechnologyBroker } from "../main/events/station/TechnologyBroker.js";
import type { AsteroidCracked } from "../main/events/trade/AsteroidCracked.js";
import type { BuyTradeData } from "../main/events/trade/BuyTradeData.js";
import type { CollectCargo } from "../main/events/trade/CollectCargo.js";
import type { EjectCargo } from "../main/events/trade/EjectCargo.js";
import type { MarketBuy } from "../main/events/trade/MarketBuy.js";
import type { MarketSell } from "../main/events/trade/MarketSell.js";
import type { MiningRefined } from "../main/events/trade/MiningRefined.js";
import type { ApproachBody } from "../main/events/travel/ApproachBody.js";
import type { Docked } from "../main/events/travel/Docked.js";
import type { DockingCancelled } from "../main/events/travel/DockingCancelled.js";
import type { DockingDenied } from "../main/events/travel/DockingDenied.js";
import type { DockingGranted } from "../main/events/travel/DockingGranted.js";
import type { DockingRequested } from "../main/events/travel/DockingRequested.js";
import type { DockingTimeout } from "../main/events/travel/DockingTimeout.js";
import type { FSDJump } from "../main/events/travel/FSDJump.js";
import type { FSDTarget } from "../main/events/travel/FSDTarget.js";
import type { LeaveBody } from "../main/events/travel/LeaveBody.js";
import type { Liftoff } from "../main/events/travel/Liftoff.js";
import type { Location } from "../main/events/travel/Location.js";
import type { ExtendedNavRoute, NavRoute } from "../main/events/travel/NavRoute.js";
import type { NavRouteClear } from "../main/events/travel/NavRouteClear.js";
import type { JumpType, StartJump } from "../main/events/travel/StartJump.js";
import type { SupercruiseEntry } from "../main/events/travel/SupercruiseEntry.js";
import type { SupercruiseExit } from "../main/events/travel/SupercruiseExit.js";
import type { Touchdown } from "../main/events/travel/Touchdown.js";
import type { Undocked } from "../main/events/travel/Undocked.js";
import type { BodyType } from "../main/events/types/BodyType.js";
import type { CarrierType } from "../main/events/types/CarrierType.js";
import type { ConflictFaction } from "../main/events/types/ConflictFaction.js";
import type { ConflictProgress } from "../main/events/types/ConflictProgress.js";
import type { ID } from "../main/events/types/ID.js";
import type { MicroResource } from "../main/events/types/MicroResource.js";
import type { PowerState, PowerState1, PowerState2 } from "../main/events/types/PowerState.js";
import type { StationService } from "../main/events/types/StationService.js";
import type { StationType } from "../main/events/types/StationType.js";
import * as exports from "../main/index.js";
import { Journal, type JournalOptions } from "../main/Journal.js";
import { JournalError } from "../main/JournalError.js";
import type { JournalEvent } from "../main/JournalEvent.js";
import type { JournalPosition, NamedJournalPosition } from "../main/JournalPosition.js";

describe("core", () => {
    it("exports relevant types and functions and nothing else", () => {
        expect({ ...exports }).toEqual({
            Journal,
            JournalError
        });

        // Interfaces and types can only be checked by TypeScript
        ((): JournalOptions => (({} as exports.JournalOptions)))();
        ((): JournalEvent => (({} as exports.JournalEvent)))();
        ((): JournalPosition => (({} as exports.JournalPosition)))();
        ((): NamedJournalPosition => (({} as exports.NamedJournalPosition)))();
        ((): EjectCargo => (({} as exports.EjectCargo)))();
        ((): MarketBuy => (({} as exports.MarketBuy)))();
        ((): AsteroidCracked => (({} as exports.AsteroidCracked)))();
        ((): BuyTradeData => (({} as exports.BuyTradeData)))();
        ((): CollectCargo => (({} as exports.CollectCargo)))();
        ((): MarketSell => (({} as exports.MarketSell)))();
        ((): MiningRefined => (({} as exports.MiningRefined)))();
        ((): Interdiction => (({} as exports.Interdiction)))();
        ((): HeatWarning => (({} as exports.HeatWarning)))();
        ((): UnderAttack => (({} as exports.UnderAttack)))();
        ((): PVPKill => (({} as exports.PVPKill)))();
        ((): FactionKillBond => (({} as exports.FactionKillBond)))();
        ((): FighterDestroyed => (({} as exports.FighterDestroyed)))();
        ((): Interdicted => (({} as exports.Interdicted)))();
        ((): Died => (({} as exports.Died)))();
        ((): HeatDamage => (({} as exports.HeatDamage)))();
        ((): Bounty => (({} as exports.Bounty)))();
        ((): ShipTargeted => (({} as exports.ShipTargeted)))();
        ((): CapShipBond => (({} as exports.CapShipBond)))();
        ((): ShieldState => (({} as exports.ShieldState)))();
        ((): SRVDestroyed => (({} as exports.SRVDestroyed)))();
        ((): EscapeInterdiction => (({} as exports.EscapeInterdiction)))();
        ((): HullDamage => (({} as exports.HullDamage)))();
        ((): ConflictFaction => (({} as exports.ConflictFaction)))();
        ((): PowerState => (({} as exports.PowerState)))();
        ((): PowerState1 => (({} as exports.PowerState1)))();
        ((): PowerState2 => (({} as exports.PowerState2)))();
        ((): BodyType => (({} as exports.BodyType)))();
        ((): StationType => (({} as exports.StationType)))();
        ((): CarrierType => (({} as exports.CarrierType)))();
        ((): MicroResource => (({} as exports.MicroResource)))();
        ((): StationService => (({} as exports.StationService)))();
        ((): ConflictProgress => (({} as exports.ConflictProgress)))();
        ((): ID => (({} as exports.ID)))();
        ((): SupercruiseExit => (({} as exports.SupercruiseExit)))();
        ((): Liftoff => (({} as exports.Liftoff)))();
        ((): ExtendedNavRoute => (({} as exports.ExtendedNavRoute)))();
        ((): NavRoute => (({} as exports.NavRoute)))();
        ((): DockingGranted => (({} as exports.DockingGranted)))();
        ((): Docked => (({} as exports.Docked)))();
        ((): NavRouteClear => (({} as exports.NavRouteClear)))();
        ((): Undocked => (({} as exports.Undocked)))();
        ((): Touchdown => (({} as exports.Touchdown)))();
        ((): DockingRequested => (({} as exports.DockingRequested)))();
        ((): ApproachBody => (({} as exports.ApproachBody)))();
        ((): DockingDenied => (({} as exports.DockingDenied)))();
        ((): LeaveBody => (({} as exports.LeaveBody)))();
        ((): DockingTimeout => (({} as exports.DockingTimeout)))();
        ((): SupercruiseEntry => (({} as exports.SupercruiseEntry)))();
        ((): FSDJump => (({} as exports.FSDJump)))();
        ((): FSDTarget => (({} as exports.FSDTarget)))();
        ((): DockingCancelled => (({} as exports.DockingCancelled)))();
        ((): Location => (({} as exports.Location)))();
        ((): JumpType => (({} as exports.JumpType)))();
        ((): StartJump => (({} as exports.StartJump)))();
        ((): NewCommander => (({} as exports.NewCommander)))();
        ((): Cargo => (({} as exports.Cargo)))();
        ((): CargoVessel => (({} as exports.CargoVessel)))();
        ((): Rank => (({} as exports.Rank)))();
        ((): Statistics => (({} as exports.Statistics)))();
        ((): Fileheader => (({} as exports.Fileheader)))();
        ((): Powerplay => (({} as exports.Powerplay)))();
        ((): Loadout => (({} as exports.Loadout)))();
        ((): Material => (({} as exports.Material)))();
        ((): Materials => (({} as exports.Materials)))();
        ((): Mission => (({} as exports.Mission)))();
        ((): Missions => (({} as exports.Missions)))();
        ((): Reputation => (({} as exports.Reputation)))();
        ((): Commander => (({} as exports.Commander)))();
        ((): ClearSavedGame => (({} as exports.ClearSavedGame)))();
        ((): GameMode => (({} as exports.GameMode)))();
        ((): LoadGame => (({} as exports.LoadGame)))();
        ((): Progress => (({} as exports.Progress)))();
        ((): Passengers => (({} as exports.Passengers)))();
        ((): SharedBookmarkToSquadron => (({} as exports.SharedBookmarkToSquadron)))();
        ((): LeftSquadron => (({} as exports.LeftSquadron)))();
        ((): SquadronPromotion => (({} as exports.SquadronPromotion)))();
        ((): SquadronDemotion => (({} as exports.SquadronDemotion)))();
        ((): SquadronStartup => (({} as exports.SquadronStartup)))();
        ((): JoinedSquadron => (({} as exports.JoinedSquadron)))();
        ((): AppliedToSquadron => (({} as exports.AppliedToSquadron)))();
        ((): SquadronCreated => (({} as exports.SquadronCreated)))();
        ((): InvitedToSquadron => (({} as exports.InvitedToSquadron)))();
        ((): DataScanned => (({} as exports.DataScanned)))();
        ((): SelfDestruct => (({} as exports.SelfDestruct)))();
        ((): Friends => (({} as exports.Friends)))();
        ((): USSDrop => (({} as exports.USSDrop)))();
        ((): LaunchSRV => (({} as exports.LaunchSRV)))();
        ((): CrewMemberQuits => (({} as exports.CrewMemberQuits)))();
        ((): WingInvite => (({} as exports.WingInvite)))();
        ((): CrimeVictim => (({} as exports.CrimeVictim)))();
        ((): JoinACrew => (({} as exports.JoinACrew)))();
        ((): Continued => (({} as exports.Continued)))();
        ((): RepairDrone => (({} as exports.RepairDrone)))();
        ((): FighterRebuilt => (({} as exports.FighterRebuilt)))();
        ((): LaunchFighter => (({} as exports.LaunchFighter)))();
        ((): ReceiveText => (({} as exports.ReceiveText)))();
        ((): ExtendedModuleInfo => (({} as exports.ExtendedModuleInfo)))();
        ((): ModuleInfo => (({} as exports.ModuleInfo)))();
        ((): DockFighter => (({} as exports.DockFighter)))();
        ((): CargoTransfer => (({} as exports.CargoTransfer)))();
        ((): FuelScoop => (({} as exports.FuelScoop)))();
        ((): CockpitBreached => (({} as exports.CockpitBreached)))();
        ((): ProspectedAsteroid => (({} as exports.ProspectedAsteroid)))();
        ((): Shutdown => (({} as exports.Shutdown)))();
        ((): SendText => (({} as exports.SendText)))();
        ((): ReservoirReplenished => (({} as exports.ReservoirReplenished)))();
        ((): Resupply => (({} as exports.Resupply)))();
        ((): VehicleSwitch => (({} as exports.VehicleSwitch)))();
        ((): Scanned => (({} as exports.Scanned)))();
        ((): RebootRepair => (({} as exports.RebootRepair)))();
        ((): Resurrect => (({} as exports.Resurrect)))();
        ((): DatalinkScan => (({} as exports.DatalinkScan)))();
        ((): KickCrewMember => (({} as exports.KickCrewMember)))();
        ((): DockSRV => (({} as exports.DockSRV)))();
        ((): AfmuRepairs => (({} as exports.AfmuRepairs)))();
        ((): WingAdd => (({} as exports.WingAdd)))();
        ((): CrewMemberJoins => (({} as exports.CrewMemberJoins)))();
        ((): SystemsShutdown => (({} as exports.SystemsShutdown)))();
        ((): Promotion => (({} as exports.Promotion)))();
        ((): CommitCrime => (({} as exports.CommitCrime)))();
        ((): LegalState => (({} as exports.LegalState)))();
        ((): Status => (({} as exports.Status)))();
        ((): JetConeDamage => (({} as exports.JetConeDamage)))();
        ((): DatalinkVoucher => (({} as exports.DatalinkVoucher)))();
        ((): Synthesis => (({} as exports.Synthesis)))();
        ((): CrewMemberRoleChange => (({} as exports.CrewMemberRoleChange)))();
        ((): JetConeBoost => (({} as exports.JetConeBoost)))();
        ((): ApproachSettlement => (({} as exports.ApproachSettlement)))();
        ((): EndCrewSession => (({} as exports.EndCrewSession)))();
        ((): WingLeave => (({} as exports.WingLeave)))();
        ((): WingJoin => (({} as exports.WingJoin)))();
        ((): CrewLaunchFighter => (({} as exports.CrewLaunchFighter)))();
        ((): SupercruiseDestinationDrop => (({} as exports.SupercruiseDestinationDrop)))();
        ((): NpcCrewPaidWage => (({} as exports.NpcCrewPaidWage)))();
        ((): QuitACrew => (({} as exports.QuitACrew)))();
        ((): LaunchDrone => (({} as exports.LaunchDrone)))();
        ((): NpcCrewRank => (({} as exports.NpcCrewRank)))();
        ((): ChangeCrewRole => (({} as exports.ChangeCrewRole)))();
        ((): Music => (({} as exports.Music)))();
        ((): CodexEntry => (({} as exports.CodexEntry)))();
        ((): SAAScanComplete => (({} as exports.SAAScanComplete)))();
        ((): Scan => (({} as exports.Scan)))();
        ((): FSSSignalDiscovered => (({} as exports.FSSSignalDiscovered)))();
        ((): SignalType => (({} as exports.SignalType)))();
        ((): BuyExplorationData => (({} as exports.BuyExplorationData)))();
        ((): Screenshot => (({} as exports.Screenshot)))();
        ((): MaterialDiscovered => (({} as exports.MaterialDiscovered)))();
        ((): NavBeaconScan => (({} as exports.NavBeaconScan)))();
        ((): MaterialCollected => (({} as exports.MaterialCollected)))();
        ((): SellExplorationData => (({} as exports.SellExplorationData)))();
        ((): SAASignalsFound => (({} as exports.SAASignalsFound)))();
        ((): ScanBaryCentre => (({} as exports.ScanBaryCentre)))();
        ((): DiscoveryScan => (({} as exports.DiscoveryScan)))();
        ((): FSSAllBodiesFound => (({} as exports.FSSAllBodiesFound)))();
        ((): FSSBodySignals => (({} as exports.FSSBodySignals)))();
        ((): MaterialDiscarded => (({} as exports.MaterialDiscarded)))();
        ((): MultiSellExplorationData => (({} as exports.MultiSellExplorationData)))();
        ((): FSSDiscoveryScan => (({} as exports.FSSDiscoveryScan)))();
        ((): CarrierNameChange => (({} as exports.CarrierNameChange)))();
        ((): CarrierDockingPermission => (({} as exports.CarrierDockingPermission)))();
        ((): CarrierJumpCancelled => (({} as exports.CarrierJumpCancelled)))();
        ((): CarrierBankTransfer => (({} as exports.CarrierBankTransfer)))();
        ((): CarrierCrewServices => (({} as exports.CarrierCrewServices)))();
        ((): CarrierFinance => (({} as exports.CarrierFinance)))();
        ((): CarrierLocation => (({} as exports.CarrierLocation)))();
        ((): CarrierTradeOrder => (({} as exports.CarrierTradeOrder)))();
        ((): CarrierModulePack => (({} as exports.CarrierModulePack)))();
        ((): CarrierModulePackBase => (({} as exports.CarrierModulePackBase)))();
        ((): CarrierModulePackBuy => (({} as exports.CarrierModulePackBuy)))();
        ((): CarrierModulePackSell => (({} as exports.CarrierModulePackSell)))();
        ((): CarrierDepositFuel => (({} as exports.CarrierDepositFuel)))();
        ((): CarrierJumpRequest => (({} as exports.CarrierJumpRequest)))();
        ((): CarrierShipPack => (({} as exports.CarrierShipPack)))();
        ((): CarrierShipPackBase => (({} as exports.CarrierShipPackBase)))();
        ((): CarrierShipPackBuy => (({} as exports.CarrierShipPackBuy)))();
        ((): CarrierShipPackSell => (({} as exports.CarrierShipPackSell)))();
        ((): CarrierJump => (({} as exports.CarrierJump)))();
        ((): CarrierBuy => (({} as exports.CarrierBuy)))();
        ((): CarrierStats => (({} as exports.CarrierStats)))();
        ((): Pack => (({} as exports.Pack)))();
        ((): PowerplayJoin => (({} as exports.PowerplayJoin)))();
        ((): PowerplayVote => (({} as exports.PowerplayVote)))();
        ((): DeliverPowerMicroResources => (({} as exports.DeliverPowerMicroResources)))();
        ((): PowerplaySalary => (({} as exports.PowerplaySalary)))();
        ((): PowerplayVoucher => (({} as exports.PowerplayVoucher)))();
        ((): PowerplayMerits => (({} as exports.PowerplayMerits)))();
        ((): PowerplayRank => (({} as exports.PowerplayRank)))();
        ((): PowerplayFastTrack => (({} as exports.PowerplayFastTrack)))();
        ((): PowerplayDeliver => (({} as exports.PowerplayDeliver)))();
        ((): PowerplayLeave => (({} as exports.PowerplayLeave)))();
        ((): PowerplayCollect => (({} as exports.PowerplayCollect)))();
        ((): PowerplayDefect => (({} as exports.PowerplayDefect)))();
        ((): ModuleStore => (({} as exports.ModuleStore)))();
        ((): MassModuleStore => (({} as exports.MassModuleStore)))();
        ((): MissionCompleted => (({} as exports.MissionCompleted)))();
        ((): MissionFailed => (({} as exports.MissionFailed)))();
        ((): StoredModules => (({} as exports.StoredModules)))();
        ((): CommunityGoalDiscard => (({} as exports.CommunityGoalDiscard)))();
        ((): ShipyardTransfer => (({} as exports.ShipyardTransfer)))();
        ((): ModuleRetrieve => (({} as exports.ModuleRetrieve)))();
        ((): ShipyardSwap => (({} as exports.ShipyardSwap)))();
        ((): Repair => (({} as exports.Repair)))();
        ((): CrewFire => (({} as exports.CrewFire)))();
        ((): SellShipOnRebuy => (({} as exports.SellShipOnRebuy)))();
        ((): ExtendedMarket => (({} as exports.ExtendedMarket)))();
        ((): Market => (({} as exports.Market)))();
        ((): CommunityGoalJoin => (({} as exports.CommunityGoalJoin)))();
        ((): Engineer => (({} as exports.Engineer)))();
        ((): EngineerBase => (({} as exports.EngineerBase)))();
        ((): EngineerProgress => (({} as exports.EngineerProgress)))();
        ((): EngineerProgressState => (({} as exports.EngineerProgressState)))();
        ((): LockedEngineer => (({} as exports.LockedEngineer)))();
        ((): UnlockedEngineer => (({} as exports.UnlockedEngineer)))();
        ((): PayBounties => (({} as exports.PayBounties)))();
        ((): ShipyardBankDeposit => (({} as exports.ShipyardBankDeposit)))();
        ((): ShipyardRedeem => (({} as exports.ShipyardRedeem)))();
        ((): ShipyardSell => (({} as exports.ShipyardSell)))();
        ((): MissionAbandoned => (({} as exports.MissionAbandoned)))();
        ((): RefuelPartial => (({} as exports.RefuelPartial)))();
        ((): EngineerContribution => (({} as exports.EngineerContribution)))();
        ((): PayFines => (({} as exports.PayFines)))();
        ((): CargoDepot => (({} as exports.CargoDepot)))();
        ((): BuyAmmo => (({} as exports.BuyAmmo)))();
        ((): BuyDrones => (({} as exports.BuyDrones)))();
        ((): ExtendedOutfitting => (({} as exports.ExtendedOutfitting)))();
        ((): Outfitting => (({} as exports.Outfitting)))();
        ((): ModuleBuyAndStore => (({} as exports.ModuleBuyAndStore)))();
        ((): EngineerApply => (({} as exports.EngineerApply)))();
        ((): SearchAndRescue => (({} as exports.SearchAndRescue)))();
        ((): ModuleSell => (({} as exports.ModuleSell)))();
        ((): CrewHire => (({} as exports.CrewHire)))();
        ((): ExtendedShipyard => (({} as exports.ExtendedShipyard)))();
        ((): Shipyard => (({} as exports.Shipyard)))();
        ((): RefuelAll => (({} as exports.RefuelAll)))();
        ((): MaterialTrade => (({} as exports.MaterialTrade)))();
        ((): TechnologyBroker => (({} as exports.TechnologyBroker)))();
        ((): CrewAssign => (({} as exports.CrewAssign)))();
        ((): RedeemVoucher => (({} as exports.RedeemVoucher)))();
        ((): SellDrones => (({} as exports.SellDrones)))();
        ((): ModuleSellRemote => (({} as exports.ModuleSellRemote)))();
        ((): ShipRedeemed => (({} as exports.ShipRedeemed)))();
        ((): MissionRedirected => (({} as exports.MissionRedirected)))();
        ((): ModuleSwap => (({} as exports.ModuleSwap)))();
        ((): EngineerCraft => (({} as exports.EngineerCraft)))();
        ((): ModuleBuy => (({} as exports.ModuleBuy)))();
        ((): FetchRemoteModule => (({} as exports.FetchRemoteModule)))();
        ((): RepairAll => (({} as exports.RepairAll)))();
        ((): CommunityGoal => (({} as exports.CommunityGoal)))();
        ((): SetUserShipName => (({} as exports.SetUserShipName)))();
        ((): EngineerLegacyConvert => (({} as exports.EngineerLegacyConvert)))();
        ((): ScientificResearch => (({} as exports.ScientificResearch)))();
        ((): CommunityGoalReward => (({} as exports.CommunityGoalReward)))();
        ((): StoredShips => (({} as exports.StoredShips)))();
        ((): MissionAccepted => (({} as exports.MissionAccepted)))();
        ((): ShipyardNew => (({} as exports.ShipyardNew)))();
        ((): ShipyardBuy => (({} as exports.ShipyardBuy)))();
        ((): RestockVehicle => (({} as exports.RestockVehicle)))();
        ((): PayLegacyFines => (({} as exports.PayLegacyFines)))();
        ((): CreateSuitLoadout => (({} as exports.CreateSuitLoadout)))();
        ((): SellMicroResources => (({} as exports.SellMicroResources)))();
        ((): DropItems => (({} as exports.DropItems)))();
        ((): Disembark => (({} as exports.Disembark)))();
        ((): BookDropship => (({} as exports.BookDropship)))();
        ((): UseConsumable => (({} as exports.UseConsumable)))();
        ((): BuyWeapon => (({} as exports.BuyWeapon)))();
        ((): TradeMicroResources => (({} as exports.TradeMicroResources)))();
        ((): UpgradeWeapon => (({} as exports.UpgradeWeapon)))();
        ((): RenameSuitLoadout => (({} as exports.RenameSuitLoadout)))();
        ((): ExtendedFCMaterials => (({} as exports.ExtendedFCMaterials)))();
        ((): FCMaterials => (({} as exports.FCMaterials)))();
        ((): SellWeapon => (({} as exports.SellWeapon)))();
        ((): CollectItems => (({} as exports.CollectItems)))();
        ((): LoadoutEquipModule => (({} as exports.LoadoutEquipModule)))();
        ((): ScanOrganic => (({} as exports.ScanOrganic)))();
        ((): UpgradeSuit => (({} as exports.UpgradeSuit)))();
        ((): BackpackChange => (({} as exports.BackpackChange)))();
        ((): ChangedBackpackItem => (({} as exports.ChangedBackpackItem)))();
        ((): SellSuit => (({} as exports.SellSuit)))();
        ((): SwitchSuitLoadout => (({} as exports.SwitchSuitLoadout)))();
        ((): Embark => (({} as exports.Embark)))();
        ((): BuySuit => (({} as exports.BuySuit)))();
        ((): BookTaxi => (({} as exports.BookTaxi)))();
        ((): CancelTaxi => (({} as exports.CancelTaxi)))();
        ((): CancelDropship => (({} as exports.CancelDropship)))();
        ((): TransferMicroResources => (({} as exports.TransferMicroResources)))();
        ((): SuitLoadout => (({} as exports.SuitLoadout)))();
        ((): DeleteSuitLoadout => (({} as exports.DeleteSuitLoadout)))();
        ((): Backpack => (({} as exports.Backpack)))();
        ((): BackpackItem => (({} as exports.BackpackItem)))();
        ((): DropshipDeploy => (({} as exports.DropshipDeploy)))();
        ((): BuyMicroResources => (({} as exports.BuyMicroResources)))();
        ((): OldBuyMicroResources => (({} as exports.OldBuyMicroResources)))();
        ((): NewBuyMicroResources => (({} as exports.NewBuyMicroResources)))();
        ((): SellOrganicData => (({} as exports.SellOrganicData)))();
        ((): ShipLocker => (({} as exports.ShipLocker)))();
        ((): ShipLockerItem => (({} as exports.ShipLockerItem)))();
    });
});
